# Generated by Django 2.1.2 on 2018-10-22 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='sort')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('is_correct', models.BooleanField(default=False, verbose_name='is correct')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='sort')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('keyword_name', models.CharField(max_length=60, unique=True, verbose_name='kw-title')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='sort')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('keyword', models.ManyToManyField(to='mainapp.Keyword')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='sort')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('max_questions', models.PositiveIntegerField(blank=True, default=0, verbose_name='Count questions')),
                ('required_correct_answers', models.PositiveIntegerField(blank=True, default=0, verbose_name='Required correct answers')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sort', models.IntegerField(blank=True, default=0, null=True, verbose_name='sort')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted', models.BooleanField(default=False, verbose_name='deleted')),
            ],
            options={
                'verbose_name': 'Категория теста',
                'verbose_name_plural': 'Категории тестов',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.TestCategory'),
        ),
        migrations.AddField(
            model_name='test',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='mainapp.Keyword'),
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='mainapp.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainapp.Question'),
        ),
    ]
