# Generated by Django 2.1.2 on 2018-10-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='keyword_name',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='title',
            field=models.CharField(max_length=60, unique=True, verbose_name='kw-title'),
        ),
    ]
